# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: 
  - main
pr:
  - main

pool:
  vmImage: ubuntu-latest

jobs:
- job: check1
  steps:
  - script: echo check1
- job: check2
  steps:
  - script: echo check2
- job: check3
  steps:
  - script: echo check3
